# Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
#hide-desktop-navigation: true
width: wide
show-mobile-header: true
head-widgets:
    - type: markets
      hide-header: true
      markets:
        - symbol: AMD
          name: Advanced Micro Devices, Inc.
        - symbol: BTC-USD
          name: Bitcoin
        - symbol: NVDA
          name: NVIDIA
        - symbol: AAPL
          name: Apple
        - symbol: MSFT
          name: Microsoft
        - symbol: INTC
          name: Intel Corporation
        - symbol: GOOGL
          name: Alphabet Inc.
        - symbol: ARM
          name: Arm Holdings plc
        - symbol: QCOM
          name: QUALCOMM Incorporated
        - symbol: TSLA
          name: Tesla, Inc.

columns:
  - size: small
    widgets:
      - type: clock
        hour-format: 24h
        timezones:
          - timezone: Europe/Paris
            label: Paris
          - timezone: America/New_York
            label: New York
          - timezone: Asia/Tokyo
            label: Tokyo

      - type: dns-stats
        service: pihole-v6
        url: http://192.168.1.47/
        username: pi.hole
        password: i need a dolar

      - type: calendar
        contrast-multiplier: 1.3
        first-day-of-week: monday

  - size: full
    widgets:
      - type: split-column
        widgets:
          - type: hacker-news
            limit: 15
            collapse-after: 5
          - type: lobsters
            sort-by: hot
            tags:
              - linux
              - security
            limit: 15
            collapse-after: 5

      - type: videos
        style: grid-cards
        cache: 12h
        limit: 42
        collapse-after: 12
        channels:
          - UC8butISFwT-Wl7EV0hUK0BQ # freeCodeCamp.org
          - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
          - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
          - UCsBjURrPoezykLs9EqgamOA # Fireship
          - UC9x0AN7BWHpCDHSm9NiJFJQ # NetworkChuck
          - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

  - size: small
    widgets:
      - type: server-stats
        cache: 30s
        servers:
          - type: local
            name: Services

      - type: weather
        location: Ankara
        units: metric # alternatively "imperial"
        hour-format: 24h # alternatively "24h"
        # Optionally hide the location from being displayed in the widget
        # hide-location: true

      - type: releases
        cache: 1d
        # Without authentication the Github API allows for up to 60 requests per hour. You can create a
        # read-only token from your Github account settings and use it here to increase the limit.
        # token: ...
        repositories:
          - glanceapp/glance
          - go-gitea/gitea
          - immich-app/immich
          - syncthing/syncthing


